variable "key_name" {
  description = "EC2 Key Pair Name"
  type        = string
  default = "arvind-terraform-key"
}

variable "instance_count" {
  description = "Number of EC2 Instances"
  default     = 16
}

variable password_length {
  description = "Length of autogenerated passwords"
  default     = 16
}

# not used, just here in case something temporary is needed
variable "placeholder_password" {
    default = "+Eej8iEqThU-+\u0026\u003cr"
}

# validated list, cannot find on the web anywhere
variable "override_special_list" {
    description = "Standard list of characters to use in linux passwords"
    default = "@#%^*(){}[]-_=+<>;:,.?~|/"
}